/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyAccountTokenRouteImport } from './routes/verify-account.$token'
import { Route as PasswordResetTokenRouteImport } from './routes/password-reset.$token'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardResultsRouteImport } from './routes/dashboard.results'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardBookingsIndexRouteImport } from './routes/dashboard.bookings.index'
import { Route as DashboardTicketBookingIdRouteImport } from './routes/dashboard.ticket.$bookingId'
import { Route as DashboardBookingSelectedFlightIdRouteImport } from './routes/dashboard.booking.$selectedFlightId'
import { Route as DashboardBookingsBookingIdViewRouteImport } from './routes/dashboard.bookings.$bookingId.view'
import { Route as DashboardBookingsBookingIdEditRouteImport } from './routes/dashboard.bookings.$bookingId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyAccountTokenRoute = VerifyAccountTokenRouteImport.update({
  id: '/verify-account/$token',
  path: '/verify-account/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetTokenRoute = PasswordResetTokenRouteImport.update({
  id: '/password-reset/$token',
  path: '/password-reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResultsRoute = DashboardResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsIndexRoute = DashboardBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBookingsRoute,
} as any)
const DashboardTicketBookingIdRoute =
  DashboardTicketBookingIdRouteImport.update({
    id: '/ticket/$bookingId',
    path: '/ticket/$bookingId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingSelectedFlightIdRoute =
  DashboardBookingSelectedFlightIdRouteImport.update({
    id: '/booking/$selectedFlightId',
    path: '/booking/$selectedFlightId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingsBookingIdViewRoute =
  DashboardBookingsBookingIdViewRouteImport.update({
    id: '/$bookingId/view',
    path: '/$bookingId/view',
    getParentRoute: () => DashboardBookingsRoute,
  } as any)
const DashboardBookingsBookingIdEditRoute =
  DashboardBookingsBookingIdEditRouteImport.update({
    id: '/$bookingId/edit',
    path: '/$bookingId/edit',
    getParentRoute: () => DashboardBookingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/verify-account/$token': typeof VerifyAccountTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/booking/$selectedFlightId': typeof DashboardBookingSelectedFlightIdRoute
  '/dashboard/ticket/$bookingId': typeof DashboardTicketBookingIdRoute
  '/dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/dashboard/bookings/$bookingId/edit': typeof DashboardBookingsBookingIdEditRoute
  '/dashboard/bookings/$bookingId/view': typeof DashboardBookingsBookingIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/verify-account/$token': typeof VerifyAccountTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/booking/$selectedFlightId': typeof DashboardBookingSelectedFlightIdRoute
  '/dashboard/ticket/$bookingId': typeof DashboardTicketBookingIdRoute
  '/dashboard/bookings': typeof DashboardBookingsIndexRoute
  '/dashboard/bookings/$bookingId/edit': typeof DashboardBookingsBookingIdEditRoute
  '/dashboard/bookings/$bookingId/view': typeof DashboardBookingsBookingIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/bookings': typeof DashboardBookingsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/results': typeof DashboardResultsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/password-reset/$token': typeof PasswordResetTokenRoute
  '/verify-account/$token': typeof VerifyAccountTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/booking/$selectedFlightId': typeof DashboardBookingSelectedFlightIdRoute
  '/dashboard/ticket/$bookingId': typeof DashboardTicketBookingIdRoute
  '/dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/dashboard/bookings/$bookingId/edit': typeof DashboardBookingsBookingIdEditRoute
  '/dashboard/bookings/$bookingId/view': typeof DashboardBookingsBookingIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/dashboard/results'
    | '/dashboard/search'
    | '/password-reset/$token'
    | '/verify-account/$token'
    | '/dashboard/'
    | '/dashboard/booking/$selectedFlightId'
    | '/dashboard/ticket/$bookingId'
    | '/dashboard/bookings/'
    | '/dashboard/bookings/$bookingId/edit'
    | '/dashboard/bookings/$bookingId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/profile'
    | '/dashboard/results'
    | '/dashboard/search'
    | '/password-reset/$token'
    | '/verify-account/$token'
    | '/dashboard'
    | '/dashboard/booking/$selectedFlightId'
    | '/dashboard/ticket/$bookingId'
    | '/dashboard/bookings'
    | '/dashboard/bookings/$bookingId/edit'
    | '/dashboard/bookings/$bookingId/view'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/bookings'
    | '/dashboard/profile'
    | '/dashboard/results'
    | '/dashboard/search'
    | '/password-reset/$token'
    | '/verify-account/$token'
    | '/dashboard/'
    | '/dashboard/booking/$selectedFlightId'
    | '/dashboard/ticket/$bookingId'
    | '/dashboard/bookings/'
    | '/dashboard/bookings/$bookingId/edit'
    | '/dashboard/bookings/$bookingId/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PasswordResetTokenRoute: typeof PasswordResetTokenRoute
  VerifyAccountTokenRoute: typeof VerifyAccountTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify-account/$token': {
      id: '/verify-account/$token'
      path: '/verify-account/$token'
      fullPath: '/verify-account/$token'
      preLoaderRoute: typeof VerifyAccountTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/$token': {
      id: '/password-reset/$token'
      path: '/password-reset/$token'
      fullPath: '/password-reset/$token'
      preLoaderRoute: typeof PasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/results': {
      id: '/dashboard/results'
      path: '/results'
      fullPath: '/dashboard/results'
      preLoaderRoute: typeof DashboardResultsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings/': {
      id: '/dashboard/bookings/'
      path: '/'
      fullPath: '/dashboard/bookings/'
      preLoaderRoute: typeof DashboardBookingsIndexRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/dashboard/ticket/$bookingId': {
      id: '/dashboard/ticket/$bookingId'
      path: '/ticket/$bookingId'
      fullPath: '/dashboard/ticket/$bookingId'
      preLoaderRoute: typeof DashboardTicketBookingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/booking/$selectedFlightId': {
      id: '/dashboard/booking/$selectedFlightId'
      path: '/booking/$selectedFlightId'
      fullPath: '/dashboard/booking/$selectedFlightId'
      preLoaderRoute: typeof DashboardBookingSelectedFlightIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings/$bookingId/view': {
      id: '/dashboard/bookings/$bookingId/view'
      path: '/$bookingId/view'
      fullPath: '/dashboard/bookings/$bookingId/view'
      preLoaderRoute: typeof DashboardBookingsBookingIdViewRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
    '/dashboard/bookings/$bookingId/edit': {
      id: '/dashboard/bookings/$bookingId/edit'
      path: '/$bookingId/edit'
      fullPath: '/dashboard/bookings/$bookingId/edit'
      preLoaderRoute: typeof DashboardBookingsBookingIdEditRouteImport
      parentRoute: typeof DashboardBookingsRoute
    }
  }
}

interface DashboardBookingsRouteChildren {
  DashboardBookingsIndexRoute: typeof DashboardBookingsIndexRoute
  DashboardBookingsBookingIdEditRoute: typeof DashboardBookingsBookingIdEditRoute
  DashboardBookingsBookingIdViewRoute: typeof DashboardBookingsBookingIdViewRoute
}

const DashboardBookingsRouteChildren: DashboardBookingsRouteChildren = {
  DashboardBookingsIndexRoute: DashboardBookingsIndexRoute,
  DashboardBookingsBookingIdEditRoute: DashboardBookingsBookingIdEditRoute,
  DashboardBookingsBookingIdViewRoute: DashboardBookingsBookingIdViewRoute,
}

const DashboardBookingsRouteWithChildren =
  DashboardBookingsRoute._addFileChildren(DashboardBookingsRouteChildren)

interface DashboardRouteChildren {
  DashboardBookingsRoute: typeof DashboardBookingsRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResultsRoute: typeof DashboardResultsRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBookingSelectedFlightIdRoute: typeof DashboardBookingSelectedFlightIdRoute
  DashboardTicketBookingIdRoute: typeof DashboardTicketBookingIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookingsRoute: DashboardBookingsRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResultsRoute: DashboardResultsRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBookingSelectedFlightIdRoute: DashboardBookingSelectedFlightIdRoute,
  DashboardTicketBookingIdRoute: DashboardTicketBookingIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PasswordResetTokenRoute: PasswordResetTokenRoute,
  VerifyAccountTokenRoute: VerifyAccountTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
